version: "3"
services:
  notebook: # Notebook
    build:
      context: .
      dockerfile: Dockerfile_jupyterNotebook
    volumes:
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/notebook/notebook_lib:/home/jovyan/work/notebook_lib
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/notebook/notebook_utils:/home/jovyan/work/notebook_utils
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/notebook/notebook_archive:/home/jovyan/work/notebook_archive
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/notebook/resultFiles:/home/jovyan/work/resultFiles
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/data:/home/jovyan/MainData
    ports:
      - 8888:8888
    container_name: notebookContainer

  pipelines: # Pipelines
    build:
      context: .
      dockerfile: Dockerfile_SnakemakePipeline
    deploy:
      resources:
        limits:
          memory: 4000m
    volumes:
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/data:/MainData
      - /home/ubuntu/MSProject/multiple_sclerosis_proj/notebook/resultFiles:/Output
    ports:
      - 80:5000
    links:
      - redis
      - celery
    container_name: pipelineContainer
  
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  celery:
    build: .
    command: "celery -A app.celery worker --loglevel=info"
    user: nobody
    links:
        - redis