FROM snakemake/snakemake

COPY notebook/installers/installer_Rpackage.R /installer_Rpackage.R
COPY pipelines/ /pipelines

RUN apt-get update && apt-get install -y r-base
RUN Rscript /installer_Rpackage.R

# Should solve calling all requirements in saperate pipeline folders
RUN pip install -r /pipelines/feature_extraction_pipeline/requirements.txt
RUN pip install -r /pipelines/pipeline_controller/requirements.txt

WORKDIR /pipelines/pipeline_controller/
ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:5000", \
"--workers", "2", "--threads", "4", "--worker-class", "gthread", "connector:app"]

#WORKDIR /pipelines/feature_extraction_pipeline
#ENTRYPOINT [ "snakemake", "--cores", "3" ]