FROM snakemake/snakemake

COPY pipelines/ /pipelines

# Should solve calling all requirements in saperate pipeline folders
RUN apt-get update && apt-get install -y r-base
RUN Rscript /pipelines/installer_Rpackage.R
RUN pip install -r /pipelines/requirements.txt

WORKDIR /pipelines/pipeline_controller/
ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:5000", \
"--workers", "2", "--threads", "4", "--worker-class", "gthread", "connector:app"]

#WORKDIR /pipelines/feature_extraction_pipeline
#ENTRYPOINT [ "snakemake", "--cores", "3" ]