FROM jupyter/base-notebook

COPY notebook/installers/installer_Rpackage.R /installer_Rpackage.R
COPY notebook/installers/requirements.txt /requirements.txt

RUN Rscript /installer_Rpackage.R
RUN pip install -r /requirements.txt