## For running in conda
name: utils_v1
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - ipykernel=6.2.0
  - r-essentials=3.6.1
  - pip:
    - feather-format==0.4.1
    - numpy==1.21.2
    - pandas==1.3.2
    - pyarrow==5.0.0
    - pytz==2021.1
    - scikit-learn==0.24.2
    - matplotlib==3.4.3
    - seaborn==0.11.2