#!/bin/bash
set -ex

BUCKET="openkbc-ms-notebook-bucket"
DIRECTORY="multiple_sclerosis_proj_notebook/notebook"
CMD="aws s3 sync /home/ec2-user/SageMaker/$DIRECTORY s3://$BUCKET"
cronjob="*/2 * * * * $CMD"

mkdir -p $DIRECTORY
chown "ec2-user":"ec2-user" $DIRECTORY --recursive
echo "$cronjob" | crontab -u "ec2-user" -