# For extract count and normalize raw count from data
#countInput: /Users/junheeyun/OpenKBC/multiple_sclerosis_proj/data/rsem_counts

#Output config
DataOutput: /MainData/
FeatureOutput: /Output/featureExtraction_by_Jun/

#Meta and Database
MetaInput: /MainData/annotation_metadata/EPIC_HCvB_metadata_baseline_updated-share.csv
MsigDBInput: /MainData/MsigDB_list/msigdb.v7.4.entrez.gmt #GMT file

# Parameters
NormalizeData:
  path: /MainData/counts_normalized/rawFiles/
  type: vst # vst or norm

RFECVrankingThreshold:
  step2: 10
  step4: 1

# for logging
logID: user1

